export const images = {
    // Logo: require("./logo.png"),
    ShowPasswordIC: require("./show-password-ic.svg").default,
    HidePasswordIC: require("./hide-password-ic.svg").default,
    UserIC: require("./user-outlined-ic.svg").default,
    // MenuIC: require("./menu-ic.svg").default,
    // SearchIC: require("./search-ic.svg").default,
    // SearchBlackIC: require("./search-black-ic.svg").default,
    // UserImg: require("./user-img.png"),
    // DownArrowIC: require("./down-arrow-ic.svg").default,
    // ProfileIC: require("./profile-ic.svg").default,
    // SettingsIC: require("./settings-ic.svg").default,
    // LogoutIC: require("./logout-ic.svg").default,
    // PagesIC: require("./pages-ic.svg").default,
    // EditIC: require("./edit-ic.svg").default,
    // DeleteIC: require("./delete-ic.svg").default,
    // EducationIC: require("./education.svg").default,
    // EmployerIC: require("./employer.svg").default,
    // ExperienceTitleIC: require("./experience-title.svg").default,
    // InstitutionIC: require("./institution.svg").default,
    // QualificationIC: require("./qualification.svg").default,
    // ReportsIC: require("./reports.svg").default,
    // UsersIC: require("./user.svg").default,
    // ContactRequestsIC: require("./contact-requests.svg").default,
    // NoDataFoundIC: require("./no-data-found.svg").default,
    // SaveIC: require("./save-ic.svg").default,
    // ListCheckIcon: require("./ic-list-check.svg").default,
    // AchivementIC: require("./achivement.svg").default,
    // CoverLetterIC: require("./cover-letter.svg").default,
    // ResponsibilityIC: require("./responsibility.svg").default,
    // SummaryIC: require("./summary.svg").default,
    // ValuesIC: require("./values.svg").default,
  };
  